name: Release

on:
  workflow_dispatch:
    inputs:
      url:
        description: CDN URL
        type: string
        required: true

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Run script
      if: ${{ inputs.url }}
      shell: bash
      run: build.sh ${{ inputs.url }}

    - name: Push to NuGet
      run: nuget push *.nupkg -ApiKey ${{ secrets.NUGET_API_KEY }} -Source https://api.nuget.org/v3/index.json
