name: Release

on:
  workflow_dispatch:
    inputs:
      url:
        description: CDN URL
        type: string
        required: true

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Prepare script
      run: chmod +x "${GITHUB_WORKSPACE}/build.sh"

    - name: Run script
      id: build-script
      shell: bash
      run: bash "${GITHUB_WORKSPACE}/build.sh" ${{ inputs.url }}

    # - name: Push to NuGet
    #   run: nuget push *.nupkg -ApiKey ${{ secrets.NUGET_API_KEY }} -Source https://api.nuget.org/v3/index.json

    - name: Push to GitHub Packages
      run: nuget push *.nupkg -ApiKey ${{ secrets.GITHUB_TOKEN }} -Source https://nuget.pkg.github.com/erri120/index.json

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ steps.build-script.outputs.CEF_VERSION }}
        files: |
          *.nupkg
