name: Release

on:
  workflow_dispatch:
    inputs:
      url:
        description: CDN URL
        type: string
        required: true

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Prepare script
      run: chmod +x "${GITHUB_WORKSPACE}/build.sh"

    - name: Run script
      shell: bash
      run: bash "${GITHUB_WORKSPACE}/build.sh" ${{ inputs.url }}

    - name: Push to NuGet
      run: nuget push *.nupkg -ApiKey ${{ secrets.NUGET_API_KEY }} -Source https://api.nuget.org/v3/index.json
